add_newline = false

format = """[╭─](bold green)$os$username$hostname$directory$git_branch$git_status$python$nodejs$rust$fill$cmd_duration
[╰─](bold green)$character"""

[os]
disabled = false
style = "bold blue"
format = "[$symbol]($style)"

[os.symbols]
Windows = "󰍲 "
Macos = "󰀵 "
Linux = "󰌽 "
Fedora = "󰣛 "
Ubuntu = "󰕈 "
Arch = "󰣇 "
Debian = "󰣚 "
Alpine = " "
Amazon = " "
CentOS = " "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "

[username]
show_always = true
style_user = "bold yellow"
style_root = "bold red"
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "bold cyan"
format = "[@$hostname]($style) "

[directory]
truncation_length = 2
truncate_to_repo = false
truncation_symbol = "…/"
style = "bold blue"
format = "[$path]($style) "

[git_branch]
symbol = " "
style = "bold purple"
format = "[$symbol$branch]($style) "

[git_status]
style = "bold red"
format = "[$all_status$ahead_behind]($style) "

[python]
symbol = " "
style = "bold yellow"
format = "[$symbol$version]($style) "

[nodejs]
symbol = " "
style = "bold green"
format = "[$symbol$version]($style) "

[rust]
symbol = " "
style = "bold red"
format = "[$symbol$version]($style) "

[cmd_duration]
min_time = 2_000
style = "bold yellow"
format = "[$duration]($style) "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"