<#
.SYNOPSIS
    Installs a local PowerShell 7 profile and its dependencies.
.DESCRIPTION
    Backs up deployment, writes an explicit module manifest and a thin AllHosts
    entry point. Only selected modules load. Dependencies use an explicit local
    store and are never installed at startup. Existing Starship config is retained.
.PARAMETER Work
    Enable Assurant work modules, preserving installed private work configuration.
    -Assurant is an alias, matching the cross-platform workstation bootstraps.
.PARAMETER Plugins
    Modules to deploy/import. Default PSFzf; add posh-git for Git completion.
.PARAMETER SkipPlugins
    Skip dependency deployment for offline installation.
.PARAMETER StarshipTheme
    Explicitly replace the theme; omission retains the current theme.
.PARAMETER Uninstall
    Restore entry points backed up on the first deployment with this installer.
.EXAMPLE
    ./Install-Profile.ps1 -Work -Plugins PSFzf,posh-git
.EXAMPLE
    ./Install-Profile.ps1 -Plugins PSFzf -SkipPlugins
#>
#requires -Version 7.0
[CmdletBinding()]
param(
    [Alias('Assurant')]
    [switch]$Work,
    [switch]$Uninstall,
    [string]$StarshipTheme,
    [string]$InstallDir = (Join-Path $HOME '.config/powershell'),
    [string]$ModuleDir = (Join-Path $HOME '.local/share/powershell/Modules'),
    [string[]]$ExcludeModules = @(),
    [string[]]$Plugins = @('PSFzf'),
    [switch]$SkipPlugins
)
$ErrorActionPreference = 'Stop'
$InstallDir = [IO.Path]::GetFullPath($InstallDir)
$ModuleDir = [IO.Path]::GetFullPath($ModuleDir)
$loader = Join-Path $InstallDir 'profile.ps1'
$hostEntryPoints = @(
    (Join-Path (Split-Path $PROFILE.CurrentUserAllHosts -Parent) 'Microsoft.PowerShell_profile.ps1'),
    (Join-Path (Split-Path $PROFILE.CurrentUserAllHosts -Parent) 'Microsoft.VSCode_profile.ps1')
)
$entryPoints = @($PROFILE.CurrentUserAllHosts) + $hostEntryPoints
$backup = Join-Path $env:LOCALAPPDATA ('PowerShellSetup/profile-backups/' + (Get-Date -Format 'yyyyMMdd-HHmmss-fff') + "-$PID")
New-Item -ItemType Directory -Path $backup -Force | Out-Null
$entryState = @()
foreach ($entry in $entryPoints) {
    $name = Split-Path $entry -Leaf
    $exists = Test-Path -LiteralPath $entry
    if ($exists) { Copy-Item -LiteralPath $entry -Destination (Join-Path $backup $name) }
    $entryState += @{ path = $entry; exists = $exists; file = $name }
}
$entryState | ConvertTo-Json | Set-Content -LiteralPath (Join-Path $backup 'entry-points.json')
if (Test-Path -LiteralPath $InstallDir) { Copy-Item -LiteralPath $InstallDir -Destination (Join-Path $backup 'config') -Recurse }
Write-Host "Backup: $backup"
$statePath = Join-Path $InstallDir 'installation-state.json'
if ($Uninstall) {
    if (-not (Test-Path -LiteralPath $statePath)) { throw 'No installation state to restore.' }
    $state = Get-Content -LiteralPath $statePath -Raw | ConvertFrom-Json
    $prior = Get-Content -LiteralPath (Join-Path $state.originalBackup 'entry-points.json') -Raw | ConvertFrom-Json
    foreach ($entry in $prior) {
        if ((Test-Path -LiteralPath $entry.path) -and
            (Get-Content -LiteralPath $entry.path -Raw) -notmatch 'Generated by Install-Profile.ps1') {
            Write-Warning "Edited entry point retained: $($entry.path)"
            continue
        }
        if ($entry.exists) { Copy-Item -LiteralPath (Join-Path $state.originalBackup $entry.file) -Destination $entry.path -Force }
        elseif (Test-Path -LiteralPath $entry.path) { Remove-Item -LiteralPath $entry.path }
    }
    $priorConfig = Join-Path $state.originalBackup 'config'
    if (Test-Path -LiteralPath $priorConfig) {
        Get-ChildItem -LiteralPath $priorConfig -Force | Copy-Item -Destination $InstallDir -Recurse -Force
    }
    Write-Host 'Restored prior entry points and configuration. New dependencies retained for recovery.'
    return
}
foreach ($dir in @($InstallDir, $ModuleDir, (Join-Path $InstallDir 'modules'), (Join-Path $InstallDir 'functions'))) {
    New-Item -ItemType Directory -Path $dir -Force | Out-Null
}
if (-not (Test-Path -LiteralPath $statePath)) { @{ originalBackup = $backup } | ConvertTo-Json | Set-Content -LiteralPath $statePath }
$core = @(Get-ChildItem -LiteralPath (Join-Path $PSScriptRoot 'modules') -Filter '*.ps1' -File |
    Where-Object { $_.Name -match '^\d{2}-' -and $_.Name -notin $ExcludeModules } | Sort-Object Name)
foreach ($file in $core) { Copy-Item -LiteralPath $file.FullName -Destination (Join-Path $InstallDir 'modules') -Force }
$workModules = @()
if ($Work) {
    $workDest = Join-Path $InstallDir 'modules/work'
    New-Item -ItemType Directory -Path $workDest -Force | Out-Null
    foreach ($file in (Get-ChildItem -LiteralPath (Join-Path $PSScriptRoot 'modules/work') -Filter '*.ps1' -File | Sort-Object Name)) {
        if ($file.Name -in $ExcludeModules) { continue }
        $dest = Join-Path $workDest $file.Name
        if (-not (Test-Path -LiteralPath $dest)) { Copy-Item -LiteralPath $file.FullName -Destination $dest }
        $workModules += 'modules/work/' + $file.Name
    }
}
Copy-Item -Path (Join-Path $PSScriptRoot '../functions/*.ps1') -Destination (Join-Path $InstallDir 'functions') -Force
Copy-Item -LiteralPath (Join-Path $PSScriptRoot 'Register-ProfileFunctions.ps1') -Destination $InstallDir -Force
if (-not $SkipPlugins) {
    foreach ($name in $Plugins) {
        if ($name -notmatch '^[A-Za-z0-9_.-]+$') { throw "Invalid plugin name: $name" }
        if (Get-ChildItem -LiteralPath $ModuleDir -Filter "$name.psd1" -Recurse -ErrorAction SilentlyContinue) { continue }
        $existing = Get-Module -ListAvailable -Name $name | Sort-Object Version -Descending | Select-Object -First 1
        if ($existing) {
            $dest = Join-Path $ModuleDir "$name/$($existing.Version)"
            New-Item -ItemType Directory -Path $dest -Force | Out-Null
            Get-ChildItem -LiteralPath $existing.ModuleBase -Force | Copy-Item -Destination $dest -Recurse -Force
            Write-Host "Copied installed $name to $dest"
        } else {
            Save-Module -Name $name -Repository PSGallery -Path $ModuleDir -ErrorAction Stop
            Write-Host "Saved $name to $ModuleDir"
        }
    }
}
[ordered]@{
    schemaVersion = 1; moduleDir = $ModuleDir; work = [bool]$Work; plugins = @($Plugins)
    coreModules = @($core | Where-Object Name -NotMatch '^99-' | ForEach-Object { 'modules/' + $_.Name })
    workModules = @($workModules)
    promptModules = @($core | Where-Object Name -Match '^99-' | ForEach-Object { 'modules/' + $_.Name })
} | ConvertTo-Json -Depth 4 | Set-Content -LiteralPath (Join-Path $InstallDir 'installed-profile.json')
Copy-Item -LiteralPath (Join-Path $PSScriptRoot 'Profile.ps1') -Destination $loader -Force
$escapedLoader = $loader.Replace("'", "''")
New-Item -ItemType Directory -Path (Split-Path $PROFILE.CurrentUserAllHosts -Parent) -Force | Out-Null
@"
# Generated by Install-Profile.ps1. Local configuration: $InstallDir
if (Test-Path -LiteralPath '$escapedLoader') { . '$escapedLoader' }
"@ | Set-Content -LiteralPath $PROFILE.CurrentUserAllHosts
foreach ($entry in $hostEntryPoints) {
    # Already backed up above. Both hosts use the shared AllHosts entry point.
    if (Test-Path -LiteralPath $entry) { Remove-Item -LiteralPath $entry }
}
if ($StarshipTheme -or -not (Test-Path -LiteralPath (Join-Path $HOME '.config/starship.toml'))) {
    $theme = if ($StarshipTheme) { $StarshipTheme } else { 'nova' }
    & (Join-Path $PSScriptRoot 'Set-StarshipConfig.ps1') -Theme $theme
}
Write-Host 'Profile installed. Open a new terminal to load it.'
