#!/usr/bin/env bash
# install.sh — copy this repo's zsh config into ~/.config/zsh/
#
# No symlinks, no per-user shim. The repo's zsh/ is copied into
# ~/.config/zsh/ (the XDG location), and ZDOTDIR is set in the system
# zshenv (/etc/zshenv or /etc/zsh/zshenv) so zsh finds it.
#
# Usage:
#   ./install.sh          # base install
#   ./install.sh --work   # also enable work modules
#   ./install.sh --uninstall
#
# Safe to re-run; managed block in the active system zshenv is replaced in place.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_DIR="$REPO/zsh"         # the dir copied into ~/.config/zsh
TARGET_DIR="$HOME/.config/zsh"
# System zshenv locations to try, in order. First existing file wins, then
# first directory that exists. Debian/Ubuntu/WSL and Arch use /etc/zsh/zshenv;
# Fedora and upstream/default builds use /etc/zshenv.
SYS_ZSHENV_CANDIDATES=(
  "/etc/zsh/zshenv"
  "/etc/zshenv"
)
MARKER_BEGIN="# >>> zsh/install.sh managed block >>>"
MARKER_END="# <<< zsh/install.sh managed block <<<"
TS="$(date +%Y%m%d%H%M%S)"

# Files inside the repo that should never be copied to ~/.config/zsh.
# - plugins/ is auto-cloned on first launch by _zplugin_load
# - install.sh is a meta file, not config
# - README/CHEATSHEET are docs, optional
EXCLUDE_PATTERNS=(
  "plugins/"
  "install.sh"
  "README.md"
  "CHEATSHEET.md"
  ".gitignore"
)

detect_sys_zshenv() {
  local cand

  for cand in "${SYS_ZSHENV_CANDIDATES[@]}"; do
    if [[ -f "$cand" ]]; then
      SYS_ZSHENV="$cand"
      return
    fi
  done

  for cand in "${SYS_ZSHENV_CANDIDATES[@]}"; do
    if [[ -d "$(dirname "$cand")" ]]; then
      SYS_ZSHENV="$cand"
      return
    fi
  done

  SYS_ZSHENV="/etc/zshenv"
}

WORK=0
UNINSTALL=0
for arg in "$@"; do
  case "$arg" in
    --work) WORK=1 ;;
    --uninstall) UNINSTALL=1 ;;
    -h|--help)
      sed -n '2,12p' "$0"
      exit 0
      ;;
    *)
      printf 'Unknown argument: %s\n' "$arg" >&2
      exit 1
      ;;
  esac
done

green()  { printf '\033[32m✓\033[0m %s\n' "$1"; }
yellow() { printf '\033[33m!\033[0m %s\n' "$1"; }
bold()   { printf '\033[1m%s\033[0m\n' "$1"; }

detect_sys_zshenv

# ---- sudo helper ---------------------------------------------------------
# Decide whether we can use sudo. We can use it if:
#   - we're root, OR
#   - we have passwordless sudo, OR
#   - we're in an interactive terminal (sudo can prompt for a password).
# In the non-interactive case without passwordless sudo, we print the
# block to add manually instead of failing partway.
SUDO=""
SUDO_OK=0
INTERACTIVE=0
[[ -t 0 && -t 1 ]] && INTERACTIVE=1

if [[ "$EUID" -eq 0 ]]; then
  SUDO_OK=1
elif command -v sudo >/dev/null 2>&1; then
  if sudo -n true 2>/dev/null; then
    SUDO="sudo"
    SUDO_OK=1
  elif [[ "$INTERACTIVE" -eq 1 ]]; then
    # Interactive: let sudo prompt for the password at write time.
    SUDO="sudo"
    SUDO_OK=1
  fi
fi

# ---- system zshenv block -------------------------------------------------
write_system_zshenv() {
  if [[ "$SUDO_OK" -ne 1 ]]; then
    yellow "Skipping $SYS_ZSHENV (no passwordless sudo)."
    yellow "Run install.sh in an interactive terminal, or add this to $SYS_ZSHENV manually:"
    yellow ""
    yellow '    if [[ -z "$XDG_CONFIG_HOME" ]]; then'
    yellow '        export XDG_CONFIG_HOME="$HOME/.config"'
    yellow '    fi'
    yellow '    if [[ -d "$XDG_CONFIG_HOME/zsh" ]]; then'
    yellow '        export ZDOTDIR="$XDG_CONFIG_HOME/zsh"'
    yellow '    fi'
    return 0
  fi

  local tmp
  tmp="$(mktemp)"
  # shellcheck disable=SC2064
  trap "rm -f '$tmp'" RETURN

  if [[ -f "$SYS_ZSHENV" ]]; then
    $SUDO cp "$SYS_ZSHENV" "$tmp"
    if grep -qF "$MARKER_BEGIN" "$tmp"; then
      sed -i "/$MARKER_BEGIN/,/$MARKER_END/d" "$tmp"
    fi
  fi

  {
    [[ -s "$tmp" ]] && cat "$tmp"
    printf '\n%s\n' "$MARKER_BEGIN"
    printf '# Auto-generated by zsh/install.sh on %s. Safe to remove manually.\n' "$(date -Iseconds)"
    printf 'if [[ -z "$XDG_CONFIG_HOME" ]]; then\n'
    printf '    export XDG_CONFIG_HOME="$HOME/.config"\n'
    printf 'fi\n'
    printf 'if [[ -d "$XDG_CONFIG_HOME/zsh" ]]; then\n'
    printf '    export ZDOTDIR="$XDG_CONFIG_HOME/zsh"\n'
    printf 'fi\n'
    printf '%s\n' "$MARKER_END"
  } > "$tmp"

  $SUDO install -m 644 "$tmp" "$SYS_ZSHENV"
  green "Updated $SYS_ZSHENV (ZDOTDIR=$TARGET_DIR)"
}

remove_managed_block_from_zshenv() {
  local target="$1"
  if [[ ! -f "$target" ]]; then return 0; fi
  if ! grep -qF "$MARKER_BEGIN" "$target"; then return 0; fi

  if [[ "$SUDO_OK" -ne 1 ]]; then
    yellow "Cannot remove managed block from $target (no sudo)."
    return 1
  fi

  local tmp
  tmp="$(mktemp)"
  $SUDO cp "$target" "$tmp"
  sed -i "/$MARKER_BEGIN/,/$MARKER_END/d" "$tmp"
  $SUDO install -m 644 "$tmp" "$target"
  rm -f "$tmp"
  yellow "Removed managed block from $target"
}

cleanup_inactive_zshenvs() {
  local cand
  [[ "$SUDO_OK" -eq 1 ]] || return 0

  for cand in "${SYS_ZSHENV_CANDIDATES[@]}"; do
    [[ "$cand" == "$SYS_ZSHENV" ]] && continue
    remove_managed_block_from_zshenv "$cand" || true
  done
}

remove_system_zshenv() {
  local cand failed=0

  for cand in "${SYS_ZSHENV_CANDIDATES[@]}"; do
    remove_managed_block_from_zshenv "$cand" || failed=1
  done

  return "$failed"
}

# ---- copy repo → ~/.config/zsh ------------------------------------------
should_exclude() {
  local rel="$1"
  for pat in "${EXCLUDE_PATTERNS[@]}"; do
    if [[ "$rel" == "$pat"* || "$rel" == "$pat" ]]; then
      return 0
    fi
  done
  # Work files are only included with --work
  if [[ "$rel" == work/* && "$WORK" -ne 1 ]]; then
    return 0
  fi
  return 1
}

copy_repo() {
  mkdir -p "$TARGET_DIR"

  # If the user previously had a symlink here, remove it so we can copy
  # files into the path directly.
  if [[ -L "$TARGET_DIR" ]]; then
    rm "$TARGET_DIR"
    yellow "Removed legacy symlink at $TARGET_DIR"
  fi

  # Use git ls-files to get tracked files only (no plugins/, no .git/, etc.)
  local files
  files=$(git -C "$REPO" ls-files zsh/)

  # Build the set of paths we expect to exist after the copy.
  local -A expected
  while IFS= read -r src; do
    local rel="${src#zsh/}"
    should_exclude "$rel" && continue
    [[ -d "$REPO/$src" ]] && continue
    expected["$rel"]=1
  done <<< "$files"

  # Copy each tracked file in.
  local copied=0
  for rel in "${!expected[@]}"; do
    local dst="$TARGET_DIR/$rel"
    mkdir -p "$(dirname "$dst")"
    cp "$REPO/zsh/$rel" "$dst"
    copied=$((copied + 1))
  done

  # Remove files that USED to be tracked but no longer are. Walk the
  # installed tree and delete any regular file that isn't in $expected
  # and isn't user-created (plugins/, work/az.env).
  local removed=0
  if [[ -d "$TARGET_DIR" ]]; then
    while IFS= read -r -d '' f; do
      local rel="${f#$TARGET_DIR/}"
      # Skip excluded/auto-managed paths
      case "$rel" in
        plugins/*|work/az.env|.zshenv.uninstalled.*) continue ;;
      esac
      # Skip directories
      [[ -d "$f" ]] && continue
      # If it's in the expected set, keep it
      [[ -n "${expected[$rel]:-}" ]] && continue
      rm "$f"
      removed=$((removed + 1))
    done < <(find "$TARGET_DIR" -type f -print0 2>/dev/null)
  fi

  green "Copied $copied files from repo into $TARGET_DIR"
  if [[ "$removed" -gt 0 ]]; then
    yellow "Removed $removed stale file(s) that are no longer in the repo"
  fi
}

# Append ZSH_WORK=1 to the installed .zshenv if --work was passed.
apply_work_flag() {
  local zshenv="$TARGET_DIR/.zshenv"
  if [[ "$WORK" -ne 1 ]]; then
    # Remove the line if it's there (in case of a re-run without --work)
    if [[ -f "$zshenv" ]] && grep -qF 'export ZSH_WORK=1' "$zshenv"; then
      sed -i '/^export ZSH_WORK=1$/d' "$zshenv"
      yellow "Removed ZSH_WORK=1 from installed .zshenv"
    fi
    return
  fi
  if [[ ! -f "$zshenv" ]]; then
    yellow "Cannot enable --work: $zshenv not found"
    return
  fi
  if ! grep -qF 'export ZSH_WORK=1' "$zshenv"; then
    printf '\n# Work modules enabled (Astra/Kubernetes/CA/SSH-agent).\nexport ZSH_WORK=1\n' >> "$zshenv"
    green "Set ZSH_WORK=1 in installed .zshenv"
  fi
}

# ---- starship theme picker --------------------------------------------
# Themes live in $REPO/../starship/ (sibling of zsh/). At install time the
# user picks one, or sets ZSH_STARSHIP_THEME to skip the prompt.
STARSHIP_THEMES_DIR="$REPO/../starship"
STARSHIP_DEFAULT_THEME="nova"

list_starship_themes() {
  local f
  for f in "$STARSHIP_THEMES_DIR"/*.toml; do
    [[ -f "$f" ]] && basename "$f" .toml
  done | sort
}

pick_starship_theme() {
  local themes
  themes=($(list_starship_themes))
  if [[ ${#themes[@]} -eq 0 ]]; then
    yellow "No starship themes found in $STARSHIP_THEMES_DIR"
    return 1
  fi

  # If user supplied one, use it.
  if [[ -n "${ZSH_STARSHIP_THEME:-}" ]]; then
    printf '%s\n' "$ZSH_STARSHIP_THEME"
    return 0
  fi

  # In an interactive terminal, prompt.
  if [[ -t 0 && -t 1 ]]; then
    local i=1 choice
    printf '\nAvailable starship themes:\n'
    for t in "${themes[@]}"; do
      printf '  %d) %s\n' "$i" "$t"
      i=$((i+1))
    done
    printf '\n'
    read -r -p "Pick a theme [1-${#themes[@]}] (default: $STARSHIP_DEFAULT_THEME): " choice
    if [[ -z "$choice" ]]; then
      printf '%s\n' "$STARSHIP_DEFAULT_THEME"
    elif [[ "$choice" =~ ^[0-9]+$ ]] && (( choice >= 1 && choice <= ${#themes[@]} )); then
      printf '%s\n' "${themes[$((choice-1))]}"
    else
      yellow "Invalid choice '$choice' — using default"
      printf '%s\n' "$STARSHIP_DEFAULT_THEME"
    fi
    return 0
  fi

  # Non-interactive: use the default.
  printf '%s\n' "$STARSHIP_DEFAULT_THEME"
}

install_starship_theme() {
  [[ -d "$STARSHIP_THEMES_DIR" ]] || {
    yellow "No starship themes directory at $STARSHIP_THEMES_DIR — skipping"
    return 0
  }

  local theme source dest
  theme="$(pick_starship_theme)"
  source="$STARSHIP_THEMES_DIR/$theme.toml"
  dest="$TARGET_DIR/starship.toml"

  if [[ ! -f "$source" ]]; then
    yellow "Starship theme '$theme' not found at $source"
    yellow "Available: $(list_starship_themes | tr '\n' ' ')"
    return 1
  fi

  mkdir -p "$TARGET_DIR"
  cp "$source" "$dest"
  green "Installed starship theme: $theme"
}

# ---- remove old-style shim ---------------------------------------------
cleanup_legacy_shim() {
  if [[ -e "$HOME/.zshenv" && ! -L "$HOME/.zshenv" ]]; then
    mv "$HOME/.zshenv" "$HOME/.zshenv.bak.$TS"
    yellow "Backed up old ~/.zshenv → ~/.zshenv.bak.$TS (no longer needed)"
  elif [[ -L "$HOME/.zshenv" ]]; then
    rm "$HOME/.zshenv"
    yellow "Removed old ~/.zshenv symlink"
  fi
}

# =========================================================================
if [[ "$UNINSTALL" -eq 1 ]]; then
  bold "==> Uninstalling"
  if [[ -d "$TARGET_DIR" || -L "$TARGET_DIR" ]]; then
    if [[ -L "$TARGET_DIR" ]]; then
      rm "$TARGET_DIR"
    else
      # Back up the user's installed config rather than deleting it.
      mv "$TARGET_DIR" "$TARGET_DIR.uninstalled.$TS"
    fi
    yellow "Removed $TARGET_DIR (backup at $TARGET_DIR.uninstalled.$TS if it was a dir)"
  fi
  remove_system_zshenv
  bold "==> Done"
  exit 0
fi

bold "==> Installing"
write_system_zshenv
cleanup_inactive_zshenvs
copy_repo
install_starship_theme
apply_work_flag
cleanup_legacy_shim

echo ""
bold "==> Done"
echo "  Open a new terminal or run:  exec zsh -l"
echo ""
echo "  Layout:"
echo "    $SYS_ZSHENV      → sets ZDOTDIR (managed)"
echo "    $TARGET_DIR        → copied from the repo"
echo "    $TARGET_DIR/.zshenv → XDG vars, starship, work env"
echo "    $TARGET_DIR/.zshrc  → all modules + starship"
echo ""
echo "  First launch auto-installs missing plugins:"
echo "    zsh-autosuggestions"
echo "    zsh-history-substring-search"
echo "    fast-syntax-highlighting"
echo ""
echo "  To re-sync after editing the repo:  ./install.sh [--work]"
echo "  To toggle work modules:             ./install.sh --work"
echo "  To remove everything:               ./install.sh --uninstall"
echo ""
echo "  Recommended tools to install:"
echo "    eza bat fd-find ripgrep fzf zoxide starship mise direnv lf nvim"

if [[ "$WORK" -eq 1 ]]; then
  echo ""
  bold "==> Action required: Azure IDs"
  echo "  Copy the template and fill in the IDs:"
  echo "      cp $TARGET_DIR/work/az.env.example $TARGET_DIR/work/az.env"
  echo "      \$EDITOR $TARGET_DIR/work/az.env"
  echo ""
  echo "  Then replace the placeholder values:"
  echo ""
  echo "      export AZ_TENANT_ID=\"<your-tenant-guid>\""
  echo "      export AZ_SUBSCRIPTION_ID=\"<your-subscription-guid>\""
  echo ""
  echo "  Find them with:"
  echo "      az account tenant list   --query '[].tenantId' -o tsv"
  echo "      az account list          --query '[].{name:name,id:id}' -o table"
  echo ""
  echo "  az.env is git-ignored so your real IDs stay local to this machine."
fi
