#!/usr/bin/env bash
# install.sh — point zsh at this repo via XDG_CONFIG_HOME
#
# The repo lives at the standard XDG location: ~/.config/zsh/
# ZDOTDIR is set in /etc/zsh/zshenv (one-time, requires sudo) so no
# per-user ~/.zshenv bootstrap file is needed.
#
# Usage:
#   ./install.sh          # base install
#   ./install.sh --work   # also enable work modules
#   ./install.sh --uninstall
#
# Safe to re-run; existing files are backed up.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_DIR="$REPO/zsh"         # the dir that becomes ~/.config/zsh
TARGET_DIR="$HOME/.config/zsh"
# System zshenv locations to try, in order. First match wins.
SYS_ZSHENV_CANDIDATES=(
  "/etc/zshenv"          # Fedora, Debian, upstream default
  "/etc/zsh/zshenv"      # Arch
  "/etc/zshenv.d/zsh"    # some other distros
)
MARKER_BEGIN="# >>> zsh/install.sh managed block >>>"
MARKER_END="# <<< zsh/install.sh managed block <<<"
TS="$(date +%Y%m%d%H%M%S)"

# Find the system zshenv we can write to. Falls back to the first candidate.
detect_sys_zshenv() {
  for cand in "${SYS_ZSHENV_CANDIDATES[@]}"; do
    if [[ -f "$cand" || -d "$(dirname "$cand")" ]]; then
      SYS_ZSHENV="$cand"
      return
    fi
  done
  SYS_ZSHENV="${SYS_ZSHENV_CANDIDATES[0]}"
}

WORK=0
UNINSTALL=0
for arg in "$@"; do
  case "$arg" in
    --work) WORK=1 ;;
    --uninstall) UNINSTALL=1 ;;
    -h|--help)
      sed -n '2,12p' "$0"
      exit 0
      ;;
    *)
      printf 'Unknown argument: %s\n' "$arg" >&2
      exit 1
      ;;
  esac
done

green()  { printf '\033[32m✓\033[0m %s\n' "$1"; }
yellow() { printf '\033[33m!\033[0m %s\n' "$1"; }
bold()   { printf '\033[1m%s\033[0m\n' "$1"; }

detect_sys_zshenv

# ---- sudo helper ---------------------------------------------------------
# Returns the prefix to use for elevated commands (empty for root).
# Sets SUDO_OK=1 if we have a usable sudo, 0 otherwise.
SUDO=""
SUDO_OK=0
if [[ "$EUID" -eq 0 ]]; then
  SUDO_OK=1
elif command -v sudo >/dev/null 2>&1; then
  # -n: non-interactive; fail if a password is required.
  if sudo -n true 2>/dev/null; then
    SUDO="sudo"
    SUDO_OK=1
  fi
fi

# ---- system zshenv block -------------------------------------------------
write_system_zshenv() {
  if [[ "$SUDO_OK" -ne 1 ]]; then
    yellow "Skipping $SYS_ZSHENV (no passwordless sudo)."
    yellow "Run install.sh in an interactive terminal, or add this to $SYS_ZSHENV manually:"
    yellow ""
    yellow '    if [[ -z "$XDG_CONFIG_HOME" ]]; then'
    yellow '        export XDG_CONFIG_HOME="$HOME/.config"'
    yellow '    fi'
    yellow '    if [[ -d "$XDG_CONFIG_HOME/zsh" ]]; then'
    yellow '        export ZDOTDIR="$XDG_CONFIG_HOME/zsh"'
    yellow '    fi'
    return 0
  fi

  local tmp
  tmp="$(mktemp)"
  # shellcheck disable=SC2064
  trap "rm -f '$tmp'" RETURN

  # Strip any prior block, keep everything else in the file.
  if [[ -f "$SYS_ZSHENV" ]]; then
    $SUDO cp "$SYS_ZSHENV" "$tmp"
    if grep -qF "$MARKER_BEGIN" "$tmp"; then
      sed -i "/$MARKER_BEGIN/,/$MARKER_END/d" "$tmp"
    fi
  fi

  {
    [[ -s "$tmp" ]] && cat "$tmp"
    printf '\n%s\n' "$MARKER_BEGIN"
    printf '# Auto-generated by zsh/install.sh on %s. Safe to remove manually.\n' "$(date -Iseconds)"
    printf 'if [[ -z "$XDG_CONFIG_HOME" ]]; then\n'
    printf '    export XDG_CONFIG_HOME="$HOME/.config"\n'
    printf 'fi\n'
    printf 'if [[ -d "$XDG_CONFIG_HOME/zsh" ]]; then\n'
    printf '    export ZDOTDIR="$XDG_CONFIG_HOME/zsh"\n'
    printf 'fi\n'
    printf '%s\n' "$MARKER_END"
  } > "$tmp"

  $SUDO install -m 644 "$tmp" "$SYS_ZSHENV"
  green "Updated $SYS_ZSHENV (ZDOTDIR=$TARGET_DIR)"
}

remove_system_zshenv() {
  if [[ ! -f "$SYS_ZSHENV" ]]; then return; fi
  if ! grep -qF "$MARKER_BEGIN" "$SYS_ZSHENV"; then return; fi
  if [[ "$SUDO_OK" -ne 1 ]]; then
    yellow "Cannot remove managed block from $SYS_ZSHENV (no sudo)."
    return 1
  fi
  local tmp
  tmp="$(mktemp)"
  $SUDO cp "$SYS_ZSHENV" "$tmp"
  sed -i "/$MARKER_BEGIN/,/$MARKER_END/d" "$tmp"
  $SUDO install -m 644 "$tmp" "$SYS_ZSHENV"
  rm -f "$tmp"
  yellow "Removed managed block from $SYS_ZSHENV"
}

# ---- repo → ~/.config/zsh bridge ----------------------------------------
link_repo() {
  mkdir -p "$(dirname "$TARGET_DIR")"

  if [[ -e "$TARGET_DIR" || -L "$TARGET_DIR" ]]; then
    if [[ -L "$TARGET_DIR" && "$(readlink -f "$TARGET_DIR")" == "$(readlink -f "$SOURCE_DIR")" ]]; then
      green "~/.config/zsh already points at the repo"
      return
    fi
    yellow "$TARGET_DIR already exists and is not a link to this repo."
    yellow "  Leaving it alone. Remove it manually if you want to relink:"
    yellow "  rm $TARGET_DIR && re-run install.sh"
    return
  fi

  ln -s "$SOURCE_DIR" "$TARGET_DIR"
  green "Linked $TARGET_DIR → $SOURCE_DIR"
}

unlink_repo() {
  if [[ -L "$TARGET_DIR" ]]; then
    rm "$TARGET_DIR"
    yellow "Removed symlink $TARGET_DIR"
  fi
}

# ---- remove old-style shim ---------------------------------------------
cleanup_legacy_shim() {
  if [[ -e "$HOME/.zshenv" && ! -L "$HOME/.zshenv" ]]; then
    mv "$HOME/.zshenv" "$HOME/.zshenv.bak.$TS"
    yellow "Backed up old ~/.zshenv → ~/.zshenv.bak.$TS (no longer needed)"
  elif [[ -L "$HOME/.zshenv" ]]; then
    rm "$HOME/.zshenv"
    yellow "Removed old ~/.zshenv symlink"
  fi
}

# =========================================================================
if [[ "$UNINSTALL" -eq 1 ]]; then
  bold "==> Uninstalling"
  unlink_repo
  remove_system_zshenv
  bold "==> Done"
  exit 0
fi

bold "==> Installing"
write_system_zshenv
link_repo
cleanup_legacy_shim

echo ""
bold "==> Done"
echo "  Open a new terminal or run:  exec zsh -l"
echo ""
echo "  Layout:"
echo "    $SYS_ZSHENV      → sets ZDOTDIR (managed)"
echo "    ~/.config/zsh        → symlink to $SOURCE_DIR"
echo "    ~/.config/zsh/.zshenv → XDG vars, starship, work env"
echo "    ~/.config/zsh/.zshrc  → all modules + starship"
echo ""
echo "  First launch auto-installs missing plugins:"
echo "    zsh-autosuggestions"
echo "    zsh-history-substring-search"
echo "    fast-syntax-highlighting"
echo ""
echo "  To toggle work modules, re-run:  ./install.sh --work"
echo "  To remove everything:           ./install.sh --uninstall"
echo ""
echo "  Recommended tools to install:"
echo "    eza bat fd-find ripgrep fzf zoxide starship mise direnv keychain nvm lf nvim"

if [[ "$WORK" -eq 1 ]]; then
  echo ""
  bold "==> Action required: Azure IDs"
  echo "  Copy the template and fill in the IDs:"
  echo "      cp $TARGET_DIR/work/az.env.example $TARGET_DIR/work/az.env"
  echo "      \$EDITOR $TARGET_DIR/work/az.env"
  echo ""
  echo "  Then replace the placeholder values:"
  echo ""
  echo "      export AZ_TENANT_ID=\"<your-tenant-guid>\""
  echo "      export AZ_SUBSCRIPTION_ID=\"<your-subscription-guid>\""
  echo ""
  echo "  Find them with:"
  echo "      az account tenant list   --query '[].tenantId' -o tsv"
  echo "      az account list          --query '[].{name:name,id:id}' -o table"
  echo ""
  echo "  az.env is git-ignored so your real IDs stay local to this machine."
fi
